In [1]:
import numpy as np

In [9]:
a = np.arange(1,11)
print('a = ', a)

a =  [ 1  2  3  4  5  6  7  8  9 10]


In [10]:
a = a[::-1]
# a = np.arange(10,1-1)
print('a = ', a)

a =  [10  9  8  7  6  5  4  3  2  1]


In [12]:
a.shape

(10,)

In [16]:
a = a.reshape(2,5)
print(a)
print(a.shape)

[[10  9  8  7  6]
 [ 5  4  3  2  1]] (2, 5)


In [18]:
a = a.reshape(5,2)
print(a)
print(a.shape)

[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]
(5, 2)


In [20]:
a = np.arange(1,17).reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [10]:
np.arange(1,13).reshape(4,-1) # 개수가 정확할때, 행은 4로 할테니 열은 알아서 맞춰줘

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
a = np.random.random(10) # 10 : 1차열 배열
print('a = ',a)
print('최대값 : ',a.max())
print('최소값 : ',a.min())
print('평균값 : ',a.mean())

a =  [0.83266529 0.42899563 0.48429504 0.48258726 0.03011919 0.76622278
 0.29337981 0.03715688 0.70442073 0.50715983]
최대값 :  0.8326652853335677
최소값 :  0.030119185619199573
평균값 :  0.45670024155366196


In [24]:
a = np.random.random((2,2)) # shpae를 튜플형태로 넣어주면 shape에 맞게 배열만들어짐
print('a = ',a)
print('최대값 : ',a.max())
print('최소값 : ',a.min())
print('평균값 : ',a.mean())

print('최대값 : ',a.max(axis=0)) # 행의 방향으로 가면서 max값 구하기

a =  [[0.43951967 0.92275943]
 [0.98553232 0.99992372]]
최대값 :  0.999923715921905
최소값 :  0.4395196683820213
평균값 :  0.8369337835395461
최대값 :  [0.98553232 0.99992372]


고차원 배열을 1차원으로 변형

In [57]:
a = np.array([[1, 1], [2, 2], [3, 3]])  
b1 = a.flatten()  # 1차원으로 변형하는 함수
print(a,'\n',b1)

[[1 1]
 [2 2]
 [3 3]] 
 [1 1 2 2 3 3]


In [58]:
b2 = a.reshape(-1)
print(a,'\n',b2)


[[1 1]
 [2 2]
 [3 3]] 
 [1 1 2 2 3 3]


        flatten()   vs   reshape(-1)
원본이 바뀌어도 불변 vs 동기화가 되어있으므로 원본이 바뀌면 바뀐다

In [59]:
a[0,0] = 100 
print(a)
print(b1)
print(b2) 

[[100   1]
 [  2   2]
 [  3   3]]
[1 1 2 2 3 3]
[100   1   2   2   3   3]


In [53]:
a.ravel()

array([1, 1, 2, 2, 3, 3])

In [29]:
a = np.array([1,2,3])
b = np.array([[4,5,6],[7,8,9]])
np.append(b,a) # 더 낮은 차원을 따르도록 합쳐진다

array([4, 5, 6, 7, 8, 9, 1, 2, 3])

In [28]:
np.append([a],b,axis=0) 
# [a]는 a배열을 2차원으로 바꾼것. axis = 0 은 행방향으로 합쳐라

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

random.rand() vs random.randn() vs random.random()
rand -> 0~1사이 균등분포를 따르는 난수값 랜덤, 소괄호없이 실행 가능
randn -> 표준정규분포를 따르는 난수값 랜덤
random -> 0~1사이 완전 랜덤, tuple형식으로 소괄호 필수

In [30]:
np.random.rand(3,3)

array([[0.37817207, 0.34790961, 0.0766522 ],
       [0.5295406 , 0.44802275, 0.06272278],
       [0.00702233, 0.78502076, 0.01356987]])

In [32]:
np.random.randint(0,10,size=20) # 0 ~ 10 까지 20개의 난수 정수값

array([2, 3, 6, 7, 1, 6, 6, 4, 1, 7, 8, 5, 4, 9, 4, 4, 4, 2, 8, 6])

In [36]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b


array([5, 7, 9])

In [3]:
'''
a = np.array([1,2])
b = np.array([4,5,6])
a+b 
'''
# shape가 맞지않아 에러

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [37]:
a*b


array([ 4, 10, 18])

In [38]:
a/b

array([0.25, 0.4 , 0.5 ])

In [39]:
np.matmul(a, b) # 행렬의곱

32

In [40]:
a @ b

32

브로드캐스팅개념 (전파, 각 개별적으로 사칙연산이 수행됨)

In [41]:
a = np.array([[1, 2], [3, 4]])
a + 1       

array([[2, 3],
       [4, 5]])

In [42]:
a - 1       

array([[0, 1],
       [2, 3]])

In [43]:
a  * 100      

array([[100, 200],
       [300, 400]])

In [45]:
a/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [46]:
a ** 2

array([[ 1,  4],
       [ 9, 16]])

In [47]:
np.zeros((2,3)) # 0으로 채우기

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.ones((2,3)) # 1로 채우기

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.full((2,3),100) # n으로 채우기

array([[100, 100, 100],
       [100, 100, 100]])

In [51]:
np.eye(3) # 단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

sum함수와  axis에 따른 원소의 합

In [11]:
a = np.arange(0,6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
a.sum(axis=1)

array([1, 5, 9])

In [13]:

a.sum(axis=0)

array([6, 9])

In [14]:
a.sum()

15

insert()함수 : 주어진 자리 앞에 추가

In [16]:
a = np.array([1,2,4])
np.insert(a,1,2)

array([1, 2, 2, 4])

In [20]:
a = np.array([[1,1],[2,2],[3,3]])
np.insert(a,1,4,axis=0) # 행 방향 index 1의 바로직전에 4를 넣어라 -> 브로드캐스팅이므로 [4,4]로 insert됨

[[1 4 1]
 [2 5 2]
 [3 6 3]]


In [ ]:
np.insert(a,1,[4,5,6],axis=1)  # 열방향 index 1의 바로직전에 [4,5,6] 을 넣어라

In [21]:
np.insert(a,1,(4,4),axis=0) # 튜플로 insert해도 리스트형태로 들어감

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

1차원 배열에서 여러개의 원소를 인덱싱 하기

In [31]:
a = np.array([3,4,5,6])
print(a[0:2])
print(a[np.array([0,1])])
print(a[np.array([0,1,3])])
print(a[np.array([0,1,1,1,1])])

[3 4]
[3 4]
[3 4 6]
[3 4 4 4 4]


In [ ]:
aList = [10, 20, 30, 40, 50, 60, 70, 80]
aList[1:5]

넘파이의 슬라이싱

In [32]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
a[1:5]     # 슬라이싱 구간 [시작:끝] 인덱스

array([20, 30, 40, 50])

In [33]:
a[1:]

array([20, 30, 40, 50, 60, 70, 80])

In [34]:
a[:] # 전체

array([10, 20, 30, 40, 50, 60, 70, 80])

In [35]:
a[::2] # 전체에서 index 2개씩 건너면서 슬라이싱

array([10, 30, 50, 70])

In [36]:
a[::-1]   

array([80, 70, 60, 50, 40, 30, 20, 10])

2차원

In [ ]:
a = np.arange(0, 6).reshape(3, 2)
print(a)

3차원의 슬라이싱

In [39]:
a = np.arange(0,24).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [43]:
print(a[1])
print(a[1,2])
print(a[1, 2, 1]) # layer 방향 1에서, 행의 방향2, 열의 방향 1


[[ 6  7]
 [ 8  9]
 [10 11]]
[10 11]
11


3차원에서의 concatenate()

In [45]:
print(a[0,0])
print(a[1,2])
np.concatenate((a[0,0],a[1,2]),axis=0)

[0 1]
[10 11]


array([ 0,  1, 10, 11])

In [46]:
np.concatenate((a[0,0,0],a[1,2,1]),axis=1)

ValueError: zero-dimensional arrays cannot be concatenated

In [50]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[9,10,11,12],[13,14,15,16],[17,18,19,20],[21,22,23,24]])
c = np.array([[25,26],[27,28]])
d = np.array([[29,30],[31,32],[33,34],[35,36]])
print(a)
print(b)
print(c)
print(d)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[25 26]
 [27 28]]
[[29 30]
 [31 32]
 [33 34]
 [35 36]]


실습문제

In [62]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [66]:
print(a>b)
print(np.greater(a,b))

[False False False False]
[False False False False]


각 중간,기말,과제 점수 가중치 .4, .4, .2를 부여하고 기타점수 5점을 더해라

In [75]:
grade = np.array([[15,100,45],[78,25,90],[81,45,99]])
result = (grade * [[0.4],[0.4],[0.2]]) 
print(result)
result.mean(axis=1)

[[11.  45.  23. ]
 [36.2 15.  41. ]
 [21.2 14.  24.8]]


array([26.33333333, 30.73333333, 20.        ])

In [76]:
mid = np.array([15,100,45])
fin = np.array([78,25,90])
hw = np.array([81,45,99])

grade2 = mid*0.4 + fin*0.4 + hw*0.2 + 5
print(grade2)

[58.4 64.  78.8]


사용자로 부터 2이상 수 n을 입력받아서 n*n 크기의 다차원 배열 a를 생성해서 배열 내용이 0과 1의 체크패턴으로 교차하여 나타나도록하여라

In [91]:
n = int(input('n을 입력하시오 : '))
a = np.zeros([n,n],dtype='int32')
for i in range(len(a)) :
    for j in range(len(b)) :
        if (i+j) % 2 == 0 :
            a[i,j] = 1

print(a)


[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


사용자로 부터 2이상 수 n을 입력받아서 n*n 크기의 1을 원소로가지는 다차원 배열 a를 생성한 후 , 테두리만1 나머지는 0인 배열 b를 생성해라

In [95]:
n = int(input('n을 입력하시오 : '))
a = np.ones([n,n], dtype='int32')
b = a
for i in range(n) :
    for j in range(n) :
        if i == 0 or j == 0 or i == (n-1) or j == (n-1) :
            pass
        else : 
            b[i,j] = 0
print(b)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [96]:
n = int(input('n을 입력하시오 : '))
a = np.ones([n,n], dtype='int32')
b = a
b[1:-1,1:-1] = 0

print(b)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [97]:
n = int(input('n을 입력하시오 : '))
a = np.zeros([n,n], dtype='int32')
b = a
b[1:-1,1:-1] = 1
print(b)

[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


In [102]:
n = int(input('n을 입력하시오 : '))
a = np.ones([n,n], dtype='int32')
b = a
b[0,:] = 0
b[-1,:] = 0
b[: ,0] = 0
b[:,-1] = 0
print(b)

[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


다음과 같은 두 배열 a,b가 있을경우 a 배열의 원소내에 b의 원소가 있는지 없는지 판단하여 출력하는 포르그램 작성
a 배열 : [ 0 10 20 40 60] 
b 배열 : [ 0 20]
[ True False True False False Flase]

In [122]:
a = np.array([0,10,20,40,60])
b = np.array([0,20]) 
t = np.full(a.shape, False)
for i in range(len(a)) :
    if a[i] in b :
        t[i] = True
print(t)

[ True False  True False False]


두 배열 a,b가 다음과 같은 원소를 가질때, 두 배열의 뺄셈을 수행하여 아래와 같이 출력하시오.
a 배열 : [ 0 10 20 40 60 80] 
b 베열 : [ 0 20]
a - b : [ 10 40 60 80]
집합연산사용X, for문과 numpy.append를 사용

In [129]:
a = np.array([0,10,20,40,60,80])
b = np.array([0,20])
c = np.array([],dtype='int32')
for x in a :
    if x not in b :
        c = np.append(c,x)
print(c)

[10 40 60 80]


정수 n을 입력받아 (n,n)shape의 정방행렬을 만든후, 대각선 성분과 그 아래값들이 모두 1이 되도록 만드시오.

In [131]:
n = int(input('n을 입력하시오 : '))
a = np.zeros([n,n],dtype='int32')
for i in range(n) :
    for j in range(n) :
        if i >= j :
            a[i,j] = 1
print(a)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


[[ 0  1  2]  [ 3  4  5]  [ 0  2  4]  [ 6  8 10]] 를 concatenate를 사용하여
[[ 0  1  2  0  2  4]  [ 3  4  5  6  8 10]] 로 만들어라.

In [144]:
a = np.array([[0,1,2],[3,4,5],[0,2,4],[6,8,10]])
b = np.concatenate((a[0],a[2]),axis=0)
c = np.concatenate((a[1],a[3]),axis=0)
print(np.array([b,c]))


[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]]


In [153]:
a = np.array([[0,0,0,0,0],[0,1,1,1,0],[0,1,2,1,0],[0,1,1,1,0],[0,0,0,0,0]])

b = a[1:4,1:4]
c = a[0:3,0:3]
d = a[0:3,1:4]
e = a[1:4,2:]
f = a[2]

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 2 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
[[1 1 1]
 [1 2 1]
 [1 1 1]]
[[0 0 0]
 [0 1 1]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [1 2 1]]
[[1 1 0]
 [2 1 0]
 [1 1 0]]
[0 1 2 1 0]


2a , a+b, a-b ,a*b , 3a - 2b , a행렬의 행 성분의 합, a행렬의 열 성분의 합

In [157]:
a = np.array([[1,1,-1],[3,2,3],[6,7,8]])
b = np.array([[1,4,-6],[0,1,1],[3,-1,6]])
print(a)
print(b)
2*a

[[ 1  1 -1]
 [ 3  2  3]
 [ 6  7  8]]
[[ 1  4 -6]
 [ 0  1  1]
 [ 3 -1  6]]


array([[ 2,  2, -2],
       [ 6,  4,  6],
       [12, 14, 16]])

In [155]:
a+b

array([[ 2,  5, -7],
       [ 3,  3,  4],
       [ 9,  6, 14]])

In [156]:
a-b

array([[ 0, -3,  5],
       [ 3,  1,  2],
       [ 3,  8,  2]])

In [158]:
a*b

array([[ 1,  4,  6],
       [ 0,  2,  3],
       [18, -7, 48]])

In [159]:
(3*a) - (2*b)

array([[ 1, -5,  9],
       [ 9,  4,  7],
       [12, 23, 12]])

In [161]:
a.sum(axis=0)

array([10, 10, 10])

In [162]:
a.sum(axis=1)

array([ 1,  8, 21])