In [2]:
import numpy as np

In [9]:
a = np.arange(1,11)
print('a = ', a)

a =  [ 1  2  3  4  5  6  7  8  9 10]


In [10]:
a = a[::-1]
# a = np.arange(10,1-1)
print('a = ', a)

a =  [10  9  8  7  6  5  4  3  2  1]


In [12]:
a.shape

(10,)

In [16]:
a = a.reshape(2,5)
print(a)
print(a.shape)

[[10  9  8  7  6]
 [ 5  4  3  2  1]] (2, 5)


In [18]:
a = a.reshape(5,2)
print(a)
print(a.shape)

[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]
(5, 2)


In [20]:
a = np.arange(1,17).reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [21]:
a = np.random.random(10) # 10 : 1차열 배열
print('a = ',a)
print('최대값 : ',a.max())
print('최소값 : ',a.min())
print('평균값 : ',a.mean())

a =  [0.83266529 0.42899563 0.48429504 0.48258726 0.03011919 0.76622278
 0.29337981 0.03715688 0.70442073 0.50715983]
최대값 :  0.8326652853335677
최소값 :  0.030119185619199573
평균값 :  0.45670024155366196


In [24]:
a = np.random.random((2,2)) # shpae를 튜플형태로 넣어주면 shape에 맞게 배열만들어짐
print('a = ',a)
print('최대값 : ',a.max())
print('최소값 : ',a.min())
print('평균값 : ',a.mean())

print('최대값 : ',a.max(axis=0)) # 행의 방향으로 가면서 max값 구하기

a =  [[0.43951967 0.92275943]
 [0.98553232 0.99992372]]
최대값 :  0.999923715921905
최소값 :  0.4395196683820213
평균값 :  0.8369337835395461
최대값 :  [0.98553232 0.99992372]


In [25]:
a = np.array([[1, 1], [2, 2], [3, 3]])  
a.flatten()   

array([1, 1, 2, 2, 3, 3])

In [29]:
a = np.array([1,2,3])
b = np.array([[4,5,6],[7,8,9]])
np.append(b,a) # 더 낮은 차원을 따르도록 합쳐진다

array([4, 5, 6, 7, 8, 9, 1, 2, 3])

In [28]:
np.append([a],b,axis=0) 
# [a]는 a배열을 2차원으로 바꾼것. axis = 0 은 행방향으로 합쳐라

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

random.rand() vs random.randn() vs random.random()
rand -> 0~1사이 균등분포를 따르는 난수값 랜덤, 소괄호없이 실행 가능
randn -> 표준정규분포를 따르는 난수값 랜덤
random -> 0~1사이 완전 랜덤, tuple형식으로 소괄호 필수

In [30]:
np.random.rand(3,3)

array([[0.37817207, 0.34790961, 0.0766522 ],
       [0.5295406 , 0.44802275, 0.06272278],
       [0.00702233, 0.78502076, 0.01356987]])

In [32]:
np.random.randint(0,10,size=20) # 0 ~ 10 까지 20개의 난수 정수값

array([2, 3, 6, 7, 1, 6, 6, 4, 1, 7, 8, 5, 4, 9, 4, 4, 4, 2, 8, 6])

In [36]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b


array([5, 7, 9])

In [34]:
'''
a = np.array([1,2])
b = np.array([4,5,6])
a+b 
'''
# shape가 맞지않아 에러

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [37]:
a*b


array([ 4, 10, 18])

In [38]:
a/b

array([0.25, 0.4 , 0.5 ])

In [39]:
np.matmul(a, b) # 행렬의곱

32

In [40]:
a @ b

32

브로드캐스팅개념 (전파, 각 개별적으로 사칙연산이 수행됨)

In [41]:
a = np.array([[1, 2], [3, 4]])
a + 1       

array([[2, 3],
       [4, 5]])

In [42]:
a - 1       

array([[0, 1],
       [2, 3]])

In [43]:
a  * 100      

array([[100, 200],
       [300, 400]])

In [45]:
a/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [46]:
a ** 2

array([[ 1,  4],
       [ 9, 16]])

In [47]:
np.zeros((2,3)) # 0으로 채우기

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.ones((2,3)) # 1로 채우기

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.full((2,3),100) # n으로 채우기

array([[100, 100, 100],
       [100, 100, 100]])

In [51]:
np.eye(3) # 단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])