## 넘파이:ML 주요 알고리즘 -선형대수와 통계에 기반

* Numpy는  Numerical Python을 의미하며 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표 패키지


* 루프를 사용치 않고 대량 데이터의 배열 연산이 가능


* C/C++과 같은 저수준 언어 기반의 호환 API제공

In [2]:
pip install scikit-learn

   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/10.6 MB 3.6 MB/s eta 0:00:03
   - -------------------------------------- 0.5/10.6 MB 7.4 MB/s eta 0:00:02
   ---- ----------------------------------- 1.1/10.6 MB 10.0 MB/s eta 0:00:01
   ------ --------------------------------- 1.8/10.6 MB 12.9 MB/s eta 0:00:01
   ---------- ----------------------------- 2.7/10.6 MB 15.9 MB/s eta 0:00:01
   -------------- ------------------------- 3.8/10.6 MB 17.2 MB/s eta 0:00:01
   ------------------- -------------------- 5.2/10.6 MB 20.6 MB/s eta 0:00:01
   ------------------------ --------------- 6.4/10.6 MB 22.7 MB/s eta 0:00:01
   ------------------------------ --------- 8.1/10.6 MB 24.6 MB/s eta 0:00:01
   ------------------------------------ --- 9.8/10.6 MB 27.2 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.6 MB 29.8 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 28.5 MB/s eta 0:

In [ ]:
import numpy as np

In [ ]:
a=[1,2,3]

In [ ]:
b=np.array([1,2,3])
print(type(a))
print(type(b))
b.shape

<class 'list'>
<class 'numpy.ndarray'>


(3,)

In [ ]:
print(a)
print(b)
type(b)

[1, 2, 3]
[1 2 3]


numpy.ndarray

In [ ]:
array1 = np.array([1,2,3])
print('arrya1 type:', type(array1))
print('array1 array 형태:',array1.shape)

arrya1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [ ]:
array2= np.array([[1,3,5],
                  [2,3,4]])
print('array2 type;', type(array2))
print('array2 array 형태:', array2.shape)

array3=np.array([[[1,2,3]]])
print('array3 type;', type(array3))
print('array3 array 형태:', array3.shape)

array2 type; <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type; <class 'numpy.ndarray'>
array3 array 형태: (1, 1, 3)


In [ ]:
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim,
                                                                 array2.ndim,
                                                           array3.ndim))

array1:1차원, array2:2차원, array3: 3차원


In [ ]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.5]
array3=np.array(list3)

print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1.  2.  3.5] float64


In [ ]:
array_int= np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1= np.array([1.1,2.1,3.5])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndrray를 편리하게 생성하기 - arange, zeros, ones

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [ ]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [ ]:
one_array=np.ones((3,2),dtype='int32')
print(one_array)
print(one_array.dtype,one_array.shape)

[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)


In [ ]:
array1= np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [ ]:
array1=np.arange(10)
array4=array1.reshape(-1,1)
print(array4,type(array4))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] <class 'numpy.ndarray'>


In [ ]:
array1=np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d\n', array3d.tolist())
array3d

array3d
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5\n', array5.tolist())
print('array5\n', array5.shape)

array5

array5
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5
 (8, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [ ]:
#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6\n',array6.tolist())
print('array6 shape:',array6.shape)

array6
 [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]]
array6 shape: (10, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

*넘파이에서 ndarray내의 일부 데이터 셋이나 특정 데이터만을 선택 할 수 있도록 하는 인덱싱에 대한 알아보자

#### 1.특정한 데이터만 추출
#### 2.슬라이싱(Slicing)
#### 3.팬시 인덱싱(Fancy Indexing)
#### 4.불린 인덱싱(Boolean Indexing)

In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
array1
print('array1:',array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index위치의 데이터 값을 의미
value=array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [ ]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 2번째 값:',array1[-2])
array1[0]=9
array1[8]=0
print('array:',array1)

맨 뒤의 값: 9 맨 뒤에서 2번째 값: 8
array: [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [ ]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


#### 2.슬라이싱(Slicing)

In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)


print(array2d)

print('array2d:\n',array2d[0:2,0:2])
print('array2d:\n',array2d[1:3,0:3])
print('array2d:\n',array2d[1:3,:])
print('array2d:\n',array2d[:,:])
print('array2d:\n',array2d[:2,1:])
print('array2d:\n',array2d[:2,0])
print('array2d:\n',array2d[:2,0:1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d:
 [[1 2]
 [4 5]]
array2d:
 [[4 5 6]
 [7 8 9]]
array2d:
 [[4 5 6]
 [7 8 9]]
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d:
 [[2 3]
 [5 6]]
array2d:
 [1 4]
array2d:
 [[1]
 [4]]


In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:',array2d[1].shape )


[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


#### 3.팬시 인덱싱(Fancy Indexing)

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2]=>',array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

array2d

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 4.불린 인덱싱(Boolean Indexing)

In [ ]:
array1d[array1d>5]

array([6, 7, 8, 9])

In [ ]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [ ]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
for i in array1d:
    if i>5:
        print(i)
    else:
        pass

6
7
8
9


In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :',array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes=np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


### 행렬의 정렬 - sort( )와 argsort( )
* 넘파이에서 행렬을 정렬하는 대표적인 방법인 np.sort()와 ndarray.sort(), 그리고 정렬된 행렬의 인덱스를 반환하는 argsort()에 대해서 알아보자.

In [ ]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 반환된 원본 행렬:', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('ndarray.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('ndarray.sort() 호출 후 반환된 원본 행렬:', org_array)


원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 반환된 원본 행렬: [3 1 9 5]
ndarray.sort() 호출 후 반환된 정렬 행렬: None
ndarray.sort() 호출 후 반환된 원본 행렬: [1 3 5 9]


In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [ ]:
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* argsort() 함수: 정렬된 행렬의 인덱스 반환!

In [ ]:
org_array = np.array([3,1,9,5])
sort_indices= np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
org_array = np.array([3,1,9,5])
sort_indices= np.argsort(org_array)[::-1]
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
#예제
name_array=['John','Mike','Sarah','Kate','Samuel']
score_array=[78,95,84,98,88]
score_array_argsort=np.argsort(score_array)
print(score_array_index,type(score_array_index))

for j in score_array_argsort:
    print(name_array[j])

[0 2 4 1 3] <class 'numpy.ndarray'>
John
Sarah
Samuel
Mike
Kate


In [ ]:
A= np.array([[1,2,3],
             [4,5,6]])
B= np.array([[7,8],
            [9,10],
           [11,12]])

dot_product=np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


###
* 전치 행렬: 원행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 그 행렬의 전치 행렬이라고 합니다. 즉 2X2 행렬 A가 있을 경우 A행렬의 1행 2열의 원소를 2행 1열의 원소로, 2행 1열의 원소를 1행 2열의 원소로 교환하는 것.

In [ ]:
A= np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치행렬:\n', transpose_mat)

B= np.array([[1,2],
            [3,4],
            [5,6]])

transpose_mat1=np.transpose(B)
print('B의 전치행렬:\n', transpose_mat1)

A의 전치행렬:
 [[1 3]
 [2 4]]
B의 전치행렬:
 [[1 3 5]
 [2 4 6]]
