In [1]:
import numpy as np

In [7]:
a = [1,2,3]
A = np.array(a)
A.shape # (3,) why? tuple형이라서
A.ndim # 1

print('A행렬의 모양은 {0}이고, 차원은 {1}이다.' .format(A.shape, A.ndim))

A행렬의 모양은 (3,)이고, 차원은 1이다.


In [ ]:
b = [[1,11,111],
     [2,22,222]]

array2d = np.array(b)
print('B행렬의 모양은 {0}이고, 차원은 {1}이다.' .format(array2d.shape, array2d.ndim))

In [8]:
c = [[1,11],
     2,22,222]

array2d = np.array(c) # 에러. 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [9]:
l2 = [1,2,'test'] # 리스트 [int,int,object]
array2d = np.array(l2) # 배열 [object,object,object]
print(array2d, array2d.dtype)

['1' '2' 'test'] <U11


In [11]:
l3 = [1,2,5.123]
array3 = np.array(l3)
print('리스트형태 : {0}, 배열형태 : {1}' .format(l3,array3))


리스트형태 : [1, 2, 5.123], 배열형태 : [1.    2.    5.123]


In [ ]:
import numpy as np
array_int = np.array([1,2,3])

ndarray 생성을 위한 편의

In [12]:
seq_array = np.arange(10)
print(seq_array)
print(seq_array.dtype, seq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [13]:
zero_array = np.zeros((3,4), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32 (3, 4)


In [14]:
ones_array = np.ones((2,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# reshape라고 하는 numpy의 모양 변형
array1 = np.arange(10)
print(array1)

print(array1.reshape(2,5))


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
### reshape 사용 이유 -> 차원을 맞추기 위해
## 1*2 행렬 X 2*1 행렬은 곱셈이 가능함 -> 딥러닝때 중요

seq_array = np.arange(1,9)

# 1차원
print(seq_array)

# 2차원
print(seq_array.reshape(4,2))

# 3차원
print(seq_array.reshape(2,2,2))


[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ndarray의 특정 데이터셋 선택 - idx

    1) 특정데이터만 추출
    2) 슬라이싱(Slicing)
    3) 팬시인덱싱(Fancy IDX)
    4) 불리언인덱싱(Boolean IDX)

In [19]:
### 1. 특정데이터만 추출
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
array1
print('array1:',array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index위치의 데이터 값을 의미
value=array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [24]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0][0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [27]:
### 2. 슬라이싱

print('array2d:\n', array2d[:,1:3])

array2d:
 [[2 3]
 [5 6]
 [8 9]]
