In [1]:
import numpy as np

1. 두 배열 a, b가 다음과 같은 원소를 가질때 , 두 배열을 이용하여 출력 결과를 도출해 보
세요.(Hint, numpy.append(x, y) 사용: x배열에 y를 더함).

실행 결과
a 배열 : [ 0 10 20 40 60 80]
b 배열 : [ 0 20]

출력결과 : [ 10 40 60 80]

In [3]:
a = np.array([0,10,20,40,60,80])
b = np.array([0,20])
c = np.array([])

for i in a :
    if i not in b :
        np.append(c,i)

print(c)

[]


2. 1에서 10까지의 정수 값을 가지는 크기가 10인 1차원 배열 a를 arange() 함수를 사용하여
생성하고, 이를 2차원 배열 (10,1)로 만들어보라.

In [9]:
a = np.arange(1,11).reshape(10,1)
print(a)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


3. 2번에서 만든 배열 (10,1)을 역순으로 sorting해 보라.

In [10]:
b = np.sort(a)[::-1]
print(b)

[[10]
 [ 9]
 [ 8]
 [ 7]
 [ 6]
 [ 5]
 [ 4]
 [ 3]
 [ 2]
 [ 1]]


4. 10부터 25까지의 수 배열을 생성하고 이를 4행 4열짜리 배열로 만든 후, 각 행과 열의 합
을 출력해 보라.

In [20]:
a = np.arange(10,26).reshape(4,4)
print('각 행의 합 : ', a.sum(axis=1))
print('각 열의 합 : ', a.sum(axis=0))

각 행의 합 :  [46 62 78 94]
각 열의 합 :  [64 68 72 76]


5. 주어진 배열 x에 대해 아래와 같은 결과가 나오도록 코드를 작성하시오. 

x : [10 20 40 60 10 20 40 40 40]

출력결과:

10 : 2번
20 : 2번
40 : 4번

In [24]:
x = np.array([10,20,40,60,10,20,40,40,40])
un = np.unique(x)
for i in un :
    count = 0
    for j in x :
        if i == j :
            count += 1
    print('{}:{}번'.format(i,count) )

10:2번
20:2번
40:4번
60:1번



6. 다음과 같은 코드가 있다
array1 = np.arange(5)
상기 array1의 차원을 2차원으로 바꾸기 위해서는 어떻게 하면 되는가?

In [29]:
array1 = np.arange(5).reshape(1,5)
array1

array([[0, 1, 2, 3, 4]])


7. 다음과 같은 3차원 배열(array3d)을 2차원으로 바꾸기 위해서는 어떻게 해야 하는가?
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))

In [12]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
array2 = array3d.reshape((1,-1))
print(array2)

[[0 1 2 3 4 5 6 7]]


8. 다음과 같이 사용자로부터 정수 n을 입력으로 받아서 (n, n) shape의 정방행렬을 만드시
오. 이 행렬의 대각선 성분과 그 아래 값들이 다음과 같이 모두 1이 되도록 만드시오. 

실행 결과

n을 입력하시오 : 5

[[1 0 0 0 0]
[1 1 0 0 0]
[1 1 1 0 0]
[1 1 1 1 0]
[1 1 1 1 1]]

In [38]:
n = int(input('n을 입력하시오 : '))
a = np.full([n,n],1)
for i in range(n) :
    for j in range(n) :
        if i < j :
            a[i][j] = 0
print(a)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


9. 다음과 같은 array가 있다고 하자. 

array2d:
[[1 2 3]
[4 5 6]
[7 8 9]]


이 array2에서 [8 9]를 뽑는 코드를 작성해 보세요.

In [41]:
array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = array2d[-1,1:3]
array2

array([8, 9])

10. 다음과 같은 name, score 두 배열이 있다고 하자. 

name = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])

score = np.array([22, 44, 84, 10, 88])

상기 배열에서 score 배열을 내림차순으로 정렬하고, 이에 따라 name 배열도 순서를 같이
정렬해 보라. 

In [21]:
name = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score = np.array([22, 44, 84, 10, 88])
c = []
for i in range(len(name)) :
    c.append((name[i],score[i]))
    
print(sorted(c))


    


[('John', 22), ('Kate', 10), ('Mike', 44), ('Samuel', 88), ('Sarah', 84)]
