1. 다음 코드의 실행 결과를 예상해 보라. 왜 그런 결과가 나오는가?

import numpy as np

a=np.array([1,2,3,4,5])

b=a[1:3]

b[0]=4

a

[1 2 3 4 5] XXX
[1 4 3 4 5] --> 배열의 Slice는 원본과 동기화됨으로

원치 않으면 .copy()를 사용하면된다.

In [1]:
import numpy as np

a=np.array([1,2,3,4,5])

b=a[1:3]

b[0]=4

a

array([1, 4, 3, 4, 5])

2. 다음 출력결과가 나오도록 ones_like라는 method를 써서, 코드를 작성하려고 한다. 밑줄에 알맞은 코드를 작성하라.

import numpy as np

a = np.array([1, 4, 3, 7, 9, 10]).reshape(2,3)

결과
array([[1, 1, 1],[1, 1, 1]])

In [2]:
import numpy as np

a = np.array([1, 4, 3, 7, 9, 10]).reshape(2,3)
a = np.ones_like(a)
a

array([[1, 1, 1],
       [1, 1, 1]])

3.
import numpy as np

a=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

위와 같은 코드를 실행한 후에, 각각 a[1, :] 과 a[1:2, :]를 실행하였다. a[1, :] 과 a[1:2, :] 의 결과를 적어보고, 이 둘의 차이에 대해 논하라.

[[1, 2, 3],
 [4, 5, 6], 
 [7, 8, 9]]

a[1, :] = [4 5 6] -> 1행, 모든열 -> 1차원

a[1:2 , :] =[[4 5 6]] -> 1~1행, 모든열 -> 2차원

In [3]:
a=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(a[1, :])
print(a[1:2, :])

[4 5 6]
[[4 5 6]]


4. 아래와 같이 a 배열이 주어져 있을 때, 출력결과와 같이 나오도록 코드를 작성해 보라. a=np.array([2,4,6,8,10]) 

출력결과 : 
array([2, 2, 2, 2, 4, 4, 6, 6])

In [49]:
'''
a = np.array([2,4,6,8,10]) 
a[:] = [2,2,2,2,4]
a
'''

a = np.array([2,4,6,8,10])
idx = np.array([0,0,0,0,1,1,2,2]) # a의 index값을 사용하여 해당 숫자를 가진 index값의 배열을 만든다
c = a[idx] # a에서 index값으로 값을 빼내어 c라는 새로운 배열 생성
c

array([2, 2, 2, 2, 4, 4, 6, 6])

5. (4,4) 배열의 표준 정규분포를 따르는 난수를 원소값으로 갖는 배열을 생성하여라. 그 다음, 배열의 원소가 양수이면 1, 음수이면 –1의 값을 갖도록 배열을 만들어 보라

In [11]:
a = np.random.randn(16).reshape(4,4)
'''
print(a)
for i in range(4) :
    for j in range(4) :
        if a[i,j] >= 0 :
            a[i,j] = 1
        else :
            a[i,j] = 0
print(a)
'''

# where 함수 : where(조건,참일때 값,거짓일때 값)
arr = np.where(a>=0,1,-1) 


[[ 1.83996838  0.12591167  1.83949844 -0.55596533]
 [-0.68007986  0.750705   -0.26188261  1.47876302]
 [ 0.10018081 -0.71302562 -0.5002132   0.81828365]
 [-0.73618252 -0.08008592  0.37341873  1.0296312 ]]
[[1. 1. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 0. 1.]
 [0. 0. 1. 1.]]


6. 아래 코드에서 만들어진 배열 arr의 원소중 양의 값을 갖는 원소의 개수를 count하는 코드를 간단히 작성해 보라.

from numpy import * 

arr = random.randn(100)

In [52]:
from numpy import * 

arr = random.randn(100)
'''
count = 0
for i in arr :
    if i>=0 :
        count +=1
print(count)
'''

a = np.where(arr>=0,1,0).sum()
print(a)
print((arr>0).sum()) # True는 1, False는 0 이라는 프로그램 언어 기본 약속~

55
55


7. 다음과 같은 사전 데이터가 있다. 

sdata = {'Ohio': 35000,
        'Texas': 71000,
        'Oregon': 16000,
        'Utah': 5000}

위의 사전데이터를 이용해 pandas의 series data로 만들어 보고, Texas의 값을 출력해 보라.

In [47]:
import pandas as pd

sdata = {'Ohio': 35000,
        'Texas': 71000,
        'Oregon': 16000,
        'Utah': 5000}

myseires = pd.Series(sdata)
print(myseires)
print(myseires['Texas'])
print(myseires.index)
print(myseires.values)
print(myseires.values[1])
# print(myseires.values('Texas'))  .key

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
71000
Index(['Ohio', 'Texas', 'Oregon', 'Utah'], dtype='object')
[35000 71000 16000  5000]
71000


8. 다음과 같은 두 배열이 있다. 출력결과대로 배열이 만들어지도록 코드를 짜보라. (힌트, concatenate, vstack 매소드 이용)

array([[1, 2, 3],
      [4, 5, 6]])
array([[ 7, 8, 9],
    [10, 11, 12]])

출력결과:
array([[ 1, 2, 3],
      [ 4, 5, 6],
      [ 7, 8, 9],
      [10, 11, 12]])

In [53]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[ 7, 8, 9],[10, 11, 12]])

print(np.concatenate((a,b), axis=0))
print(np.vstack((a,b)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



9. (5,5) 사이즈의 배열을 표준정규분포를 따르는 난수를 발생시켜 만들어보고, 만들어진 배열과 배열의 전치행렬을 이용하여 두배열의 곱(내적)을 계산하라.

In [31]:
a = np.random.randn(25).reshape(5,5)
b = a @ a.T
b

array([[15.3191812 , -0.25695301, -4.22767161,  4.99086531,  5.55323388],
       [-0.25695301,  0.97379562, -0.32843854,  0.13168837,  0.047419  ],
       [-4.22767161, -0.32843854,  2.55260646, -1.50427547, -1.72697352],
       [ 4.99086531,  0.13168837, -1.50427547,  2.4351964 ,  1.00493346],
       [ 5.55323388,  0.047419  , -1.72697352,  1.00493346,  3.11061895]])

10. (4,4) 사이즈의 배열을 표준정규분포를 따르는 난수를 발생시켜 만들어보고, 이를 dataframe으로 변환하라. 그리고 dataframe의 index 1과 2의 값을 같이 출력해보라.

In [54]:
a = np.random.randn(16).reshape(4,4)
b = pd.DataFrame(a)
print(b.loc[1:2])
print(b.iloc[1:3])

          0         1         2         3
1  1.755657  0.133335  0.721286 -1.230199
2 -0.636414  0.065331  1.316702  0.462782
          0         1         2         3
1  1.755657  0.133335  0.721286 -1.230199
2 -0.636414  0.065331  1.316702  0.462782
