In [1]:
import re

1. “abcdefg” 라는 문자열에서 ‘cde’라는 문자열을 뽑아내고 싶다. 정규표현식으로 코드를 구현해 보라. 이때 ‘.’를 활용해 구현해보라


In [5]:
m = re.findall('c.e','abcdefg')
m

['cde']

2.random.random() 함수를 사용하여 20개의 난수값을 생성하여 다음과 같이 출력하시오. 그리고 이 수들 중에서 최댓값, 최솟값, 평균값을 각각 출력하시오.

In [9]:
import numpy as np

a = np.random.random(20)
print(a)
print(max(a))
print(min(a))
print(a.mean())

[0.3302002  0.62767281 0.97896882 0.41088767 0.79290553 0.77784486
 0.34213502 0.14714295 0.4228869  0.00225672 0.66150961 0.04179759
 0.23554913 0.94499319 0.04965833 0.24101455 0.15874905 0.45048853
 0.27240986 0.31862981]
0.9789688223812826
0.00225671715071718
0.41038505623076293


3. 1에서 10까지의 정수 값을 가지는 크기가 10인 1차원 배열 a를 arange() 함수를 사용하여 생성한 후, 다음과 같은 배열로 만들어보라.

[[10 9 8 7 6]
[ 5 4 3 2 1]]

In [12]:
a = np.arange(10,0,-1).reshape(2,5)
print(a)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


4. 다음과 같은 문자열이 있다.

lyrics = 'Half of my heart is in Havana’

lyrics라는 문자열을 split() 메소드로 구분하여 각 단어를 추출한 후 for문 안에서 각 단어에 대한 upper() 메소드를 적용하여 다음과 같은 결과가 나오도록 출력해보라.

결과:
[('Half', 'HALF'), ('of', 'OF'), ('my', 'MY'), ('heart', 'HEART'), ('is', 'IS'), ('in', 'IN'),
('Havana', 'HAVANA')]

In [18]:
lyrics = 'Half of my heart is in Havana'
lyric = re.split(' ', lyrics)
result = []
for i in lyric :
    result.append((i,i.upper()))

print(result)

[('Half', 'HALF'), ('of', 'OF'), ('my', 'MY'), ('heart', 'HEART'), ('is', 'IS'), ('in', 'IN'), ('Havana', 'HAVANA')]


5. 다음과 같은 문자열이 있다.

 “abbcdeeee”

여기서 “abbc”가 뽑히도록 정규표현식을 이용해 코딩해 보라. 정규표현식에는 {} 들어가도록 해보아라.

In [19]:
text = 'abbcdeeee'
re.findall('ab{2}c',text)

['abbc']


6. 1에서 6까지의 수열 리스트를 생성하고, 이를 numpy 배열로 만들어라. 이때 만들어진 배열은 2차원 배열이 되도록 해보아라. 

In [20]:
print(np.arange(1,7).reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


7. 정규표현식에서 ?, *, + 의 의미는 무엇인가?

? : 하나 (or 1)
* : 0개 이상
+ : 1개 이상

8. 1에서 100사이의 정수 값들 중에서 6의 배수를 new_list에 담아서 다음과 같이 출력하여라. 

실행 결과 
new_list = [6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]

이때, filter() 함수와 람다 표현식을 사용하여 문제를 해결하여라.


In [23]:
new_list = list(filter(lambda x : x%6 == 0 , np.arange(1,101)))
print(new_list)

[6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]


9. 다음의 결과를 예상해 보시오.

import re

r=re.compile("[abc][y]")

r.findall("Today is Monday")

['ay','ay']

10. 다음의 결과는?

import re

r=re.compile("[^abc]")

r.search("desk")

1) None 2) ‘desk’ 3) ‘d’ 4) ‘c’

1.None

In [28]:
import re

r=re.compile("[^abc]")

r.search("desk")

<re.Match object; span=(0, 1), match='d'>